### PR TITLE
Remove resources from `parser`

### PR DESCRIPTION
**Pull request by msbit**
Remove the unused string value resource (`app_name`) from `parser`

### CODE REVIEW

**Comment by msbit** [comment]
My feeling is that this would be safe to remove.

Thoughts?

**Comment by ticofab** [comment]
Thanks for this PR!

> My feeling is that this would be safe to remove.
Have you tried running the tests and an example app without it? :)

**Comment by msbit** [comment]
Tests are good (now that I've worked out where the output goes!):

```
05-10 09:15:05.698 18380 18404 I TestRunner: run started: 7 tests
05-10 09:15:05.699 18380 18404 I TestRunner: started: testShoresOfDerwentwater(io.ticofab.androidgpxparser.parser.GPXParserTest)
05-10 09:15:05.720 18380 18404 I TestRunner: finished: testShoresOfDerwentwater(io.ticofab.androidgpxparser.parser.GPXParserTest)
05-10 09:15:05.722 18380 18404 I TestRunner: started: testGarminBaseCampExport(io.ticofab.androidgpxparser.parser.GPXParserTest)
05-10 09:15:05.744 18380 18404 I TestRunner: finished: testGarminBaseCampExport(io.ticofab.androidgpxparser.parser.GPXParserTest)
05-10 09:15:05.746 18380 18404 I TestRunner: started: testWadlbeisserExport(io.ticofab.androidgpxparser.parser.GPXParserTest)
05-10 09:15:05.935 18380 18404 I TestRunner: finished: testWadlbeisserExport(io.ticofab.androidgpxparser.parser.GPXParserTest)
05-10 09:15:05.937 18380 18404 I TestRunner: started: testGarminBaseCampExportTruncated(io.ticofab.androidgpxparser.parser.GPXParserTest)
05-10 09:15:05.940 18380 18404 I TestRunner: finished: testGarminBaseCampExportTruncated(io.ticofab.androidgpxparser.parser.GPXParserTest)
05-10 09:15:05.941 18380 18404 I TestRunner: started: testFullMetadataParsing(io.ticofab.androidgpxparser.parser.GPXParserTest)
05-10 09:15:05.944 18380 18404 I TestRunner: finished: testFullMetadataParsing(io.ticofab.androidgpxparser.parser.GPXParserTest)
05-10 09:15:05.946 18380 18404 I TestRunner: started: testMinimalMetadataParsing(io.ticofab.androidgpxparser.parser.GPXParserTest)
05-10 09:15:05.948 18380 18404 I TestRunner: finished: testMinimalMetadataParsing(io.ticofab.androidgpxparser.parser.GPXParserTest)
05-10 09:15:05.950 18380 18404 I TestRunner: started: testGarminBaseCampExportNoClosingTag(io.ticofab.androidgpxparser.parser.GPXParserTest)
05-10 09:15:05.953 18380 18404 I TestRunner: finished: testGarminBaseCampExportNoClosingTag(io.ticofab.androidgpxparser.parser.GPXParserTest)
05-10 09:15:05.955 18380 18404 I TestRunner: run finished: 7 tests, 0 failed, 0 ignored
```

Will check with a standalone app, then report back.

**Comment by msbit** [comment]
Stand-alone app works fine with:

```
implementation group: 'com.github.msbit', name: 'android-gpx-parser', version: '83b757fadd04e6eccd4112682ba890b960cbe254'
```

as a dependency.

The only difference is that if you:

* have `implementation group: 'com.github.ticofab', name: 'android-gpx-parser', version: 'v2.0.0'` as a dependency; and
* omit a string resource for `app_name`

then this resource value (`parser`) will be sourced from this library and merged in wherever it is used (usually `AndroidManifest.xml`).

My guess is that this is not intended (and I'd be very surprised if anyone is relying on that, given that `app_name` is a resource provided as part of a new Android Studio project).

**Comment by ticofab** [comment]
Merged, thanks @msbit !

**Pull request merged**
