### PR TITLE
Added custom extensions support for points and segments

### PR DESCRIPTION
**Pull request by savked**
Solves #54 

I was in need of the same thing and decided to contribute. However I was more in a need of an extension for segments, but the principle is the same so I added for both segments and points.

I have only added an extension in first segment and point for testing, feel free to edit that and perhaps include the extensions in logging of the test activity.

### CODE REVIEW

**Comment by ticofab** [comment]
Thanks for opening this PR. Will give a look as soon as possible!

**Comment by ticofab** [comment]
Hey @savked , thanks a lot for this PR! I merged it into the branch called "road-to-2.4.0", and one of the tests fails. It would be great if you could fix that 🙏 And maybe also modify the README file to explain the new feature :) Thanks again!

**Comment by savked** [comment]
No problem! I didn't look at the tests, sorry about that. Will check it out sometime soon!

**Comment by martin-gudmundson** [comment]
@ticofab & @savked 
I had need of nested extensions (and also write support). I made a fork and did the changes i needed. It's breaking changes since i've removed your Extensions class but maybe you find it interesting for a potential 3.0 rewrite. I'm sorry I don't have time to create a PR for this myself at the moment. You can check it out in my fork here: https://github.com/martin-gudmundson/android-gpx-parser

Thanks for a nice framework!

**Pull request merged**
