### PR TITLE
Change `Point` constructor to `protected`

### PR DESCRIPTION
**Pull request by msbit**
Change the `Point` constructor from the default `package-private`
access to `protected`

### CODE REVIEW

**Comment by ticofab** [comment]
Hey @msbit , thanks for opening this PR! 
What is the purpose/use case of this change?

**Comment by msbit** [comment]
Ha yes, I was thinking it would tighten up where/how a `Point` could be instantiated because otherwise you could do something like:

```
WayPoint.Builder builder = new WayPoint.Builder();
Point point = new Point(builder);
```

but then when I actually tried to put that together, I get:

```
error: Point is abstract; cannot be instantiated
```

(of course).

It's up to you whether that additional `protected` is useful signal, or confusing noise, I'm happy either way now that I've _actually_ tested it out :)

**Comment by ticofab** [comment]
Thanks for testing it out and your comment. I'd rather keep things consistent so I'm going to close it without merging and thanks again for your PR and inputs!

**Comment by msbit** [comment]
Yep all good mate.

**Pull request closed without merging**
